---
version: "3.0"
services:
  app73:
    build:
      context: .
      args:
        PHP_VERSION: 7.3
    environment:
      PHP_IDE_CONFIG: "serverName=icanboogie-datetime"
    volumes:
      - .:/app:delegated
      - ~/.composer:/root/.composer:delegated
    working_dir: /app
  app81:
    build:
      context: .
      args:
        PHP_VERSION: 8.1
    environment:
      PHP_IDE_CONFIG: "serverName=icanboogie-datetime"
    volumes:
      - .:/app:delegated
      - ~/.composer:/root/.composer:delegated
    working_dir: /app
